security:

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        in_database:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            pattern: ^/
            provider: in_database
            form_login:
                login_path: security_login
                check_path: security_login
            logout:
                path: security_logout
                target: home
            guard:
                authenticators:
                    - App\Builder\User\LoginUserBuilder

    access_control:
        - { path: ^/figure/ajouter, roles: ROLE_USER }
        - { path: ^/figure/modifier, roles: ROLE_USER }
        - { path: ^/figure/supprimer, roles: ROLE_USER }
        - { path: ^/compte, roles: ROLE_USER }
